DROP TABLE IF EXISTS PRICE;
DROP TABLE IF EXISTS BRAND;

CREATE TABLE BRAND (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE PRICE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID BIGINT,
    PRIORITY INT,
    PRICE DECIMAL(10, 2),
    CURR VARCHAR(3),
    CONSTRAINT FK_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
);